### ISSUE TITLE
KeyError: 'geoip_data'

### ISSUE THREAD

**Issue by mrazizi** [furlongm/openvpn-monitor#102]
Hi,
I've installed openvpn-monitor using **virtualenv + pip + gunicorn** method on **Ubuntu 16.04.5 LTS.** When I run openvpn-monitor using gunicorn, after opening **myip:1111/**, I get this:
`Error: 500 Internal Server Error`

<br>

This is the log message:
```
(openvpn-monitor) root@aguk:/srv/openvpn-monitor# gunicorn openvpn-monitor -b 0.0.0.0:1111
[2019-02-15 14:12:35 -0500] [10100] [INFO] Starting gunicorn 19.9.0
[2019-02-15 14:12:35 -0500] [10100] [INFO] Listening at: http://0.0.0.0:1111 (10100)
[2019-02-15 14:12:35 -0500] [10100] [INFO] Using worker: sync
[2019-02-15 14:12:35 -0500] [10103] [INFO] Booting worker with pid: 10103
WARNING: Config file does not exist or is unreadable: ./openvpn-monitor.conf
INFO: Using config file: /srv/openvpn-monitor/etc/openvpn-monitor.conf
Traceback (most recent call last):
  File "/srv/openvpn-monitor/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/srv/openvpn-monitor/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/srv/openvpn-monitor/lib/python3.5/site-packages/openvpn-monitor.py", line 854, in get_slash
    return render()
  File "/srv/openvpn-monitor/lib/python3.5/site-packages/openvpn-monitor.py", line 842, in render
    main(**kwargs)
  File "/srv/openvpn-monitor/lib/python3.5/site-packages/openvpn-monitor.py", line 803, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "/srv/openvpn-monitor/lib/python3.5/site-packages/openvpn-monitor.py", line 182, in __init__
    geoip_data = cfg.settings['geoip_data']
KeyError: 'geoip_data'
```

<br>

**/srv/openvpn-monitor/etc/openvpn-monitor.conf** : 
```
[vpn-monitor]
site=Example
#logo=logo.jpg
#latitude=40.72
#longitude=-74
maps=True
geoip_data=/var/lib/GeoIP/GeoLite2-City.mmdb
datetime_format=%d/%m/%Y %H:%M:%S

[VPN1]
host=localhost
port=5555
name=Staff VPN
show_disconnect=False
```

<br>

**/etc/openvpn/server.conf** : 
```
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
management 127.0.0.1 5555
```

Am I doing something wrong?

**Comment by CyberCam1969** [comment]
I had the same problem.... on my CentOS install the GeoIP package installed it in /usr/share/GeoIP install of /var/lib/GeoIP/ So check there.

**Comment by furlongm** [comment]
The pip version is somewhat outdated. I'll put the latest version up soon.
