### ISSUE TITLE
Client list parsing issue for TAP and IPv4+IPv6 at ovpn 2.4.7

### ISSUE THREAD

**Issue by mathiashro** [furlongm/openvpn-monitor#153]
Currently I'm experimenting with this nice project to replace a former php based VPN status webpage. 

It's working well for TUN and IPv4+IPv6 connected clients. But I do get an empty client list for TAP and IPv4+IPv6 clients. I'm not sure if the issue regarding the combination of TAP and IPv6. I've seen the recent successful pull requests #145 and #146 .

HTML Output
```<table id="sessions" class="table table-striped table-bordered 
table-hover table-condensed table-responsive 
tablesorter tablesorter-bootstrap">
<thead><tr>
<th>Username / Hostname</th>
<th>VPN IP</th>
<th>Remote IP</th>
<th>Location</th>
<th>Bytes In</th>
<th>Bytes Out</th>
<th>Connected Since</th>
<th>Last Ping</th>
<th>Time Online</th>
</tr></thead><tbody>
</tbody></table>```

The debug output is showing:
``` === begin raw data
TITLE	OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
TIME	Sat May  2 12:27:34 2020	1588415254
HEADER	CLIENT_LIST	Common Name	Real Address	Virtual Address	Virtual IPv6 Address	Bytes Received	Bytes Sent	Connected Since	Connected Since (time_t)	Username	Client ID	Peer ID
CLIENT_LIST	user1	fd32:1111:2222:0:618:d6ff:fe0c:b5ef			524960	2827402	Sat May  2 10:42:30 2020	1588408950	UNDEF	47	6
CLIENT_LIST	user2	192.168.1.1:39270			1543348892	27150470631	Fri May  1 08:36:00 2020	1588314960	UNDEF	0	0
...
HEADER	ROUTING_TABLE	Virtual Address	Common Name	Real Address	Last Ref	Last Ref (time_t)
ROUTING_TABLE	27:11:12:13:1e:c9	userX	192.168.1.3:35803	Sat May  2 12:27:31 2020	1588415251
ROUTING_TABLE	e6:22:23:24:69:a7	userY	192.168.1.2:56143	Sat May  2 11:37:11 2020	1588412231
...
GLOBAL_STATS	Max bcast/mcast queue length	6
END```

And later on:
```DEBUG:
 === begin sessions
{'': {u'bytes_recv': 8262782,
      u'bytes_sent': 7660239,
      u'client_id': u'44',
      u'connected_since': datetime.datetime(2020, 5, 2, 6, 6, 5),
      u'last_seen': datetime.datetime(2020, 5, 2, 12, 27, 31),
      u'local_ip': u'',
      u'location': u'RFC1918',
      u'peer_id': u'1',
      u'port': 35803,
      u'remote_ip': IPv4Address('192.168.2.50'),
      u'username': u'user3'}}
=== end sessions
DEBUG:
 === begin vpns
{'VPN1': {'host': 'localhost',
          'name': 'Staff VPN',
          'port': '<port>',
          u'release': u'OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019',
          u'sessions': {'': {u'bytes_recv': 8262782,
                             u'bytes_sent': 7660239,
                             u'client_id': u'44',
                             u'connected_since': datetime.datetime(2020, 5, 2, 6, 6, 5),
                             u'last_seen': datetime.datetime(2020, 5, 2, 12, 27, 31),
                             u'local_ip': u'',
                             u'location': u'RFC1918',
                             u'peer_id': u'1',
                             u'port': 35803,
                             u'remote_ip': IPv4Address('192.168.1.y'),
                             u'username': u'<username>'}},
          'show_disconnect': False,
          u'socket_connected': True,
          u'state': {u'connected': u'CONNECTED',
                     u'local_ip': u'',
                     u'mode': u'Server',
                     u'remote_ip': u'',
                     u'success': u'SUCCESS',
                     u'up_since': datetime.datetime(2020, 5, 1, 8, 35, 6)},
          u'stats': {u'bytesin': 1596890922,
                     u'bytesout': 27337944047,
                     u'nclients': 5},
          u'version': Version('2.4.7')}}
=== end vpns```

I've replaced some IPs  / names and truncated due to privacy reasons. How can I further debug this issue and/or support solving a possible parsing issue?

**Comment by furlongm** [comment]
https://github.com/furlongm/openvpn-monitor/issues/144#issuecomment-607254905 mentions that tap+ipv6 doesn't work but I don't think I tried a combination of ipv4 and ipv6.

`local_ip` seems to be empty in your debug output, which is odd. Do you have the html debug output?

**Comment by mathiashro** [comment]
Thanks for your kind answer. I've created above input via `python openvpn-monitor.py -d` and copied the table from the HTML and other other debug output. Sadly the HTML output will be visible as interpreted html snipped.

Let's try it here:

`
table id="sessions" class="table table-striped table-bordered 
table-hover table-condensed table-responsive 
tablesorter tablesorter-bootstrap">
thead><tr>
th>Username / Hostname</th>
th>VPN IP</th>
th>Remote IP</th>
th>Location</th>
th>Bytes In</th>
th>Bytes Out</th>
th>Connected Since</th>
th>Last Ping</th>
th>Time Online</th>
/tr></thead><tbody>
/tbody></table></div>
/div>
div class="panel-footer panel-custom">
OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
/div>
/div>
DEBUG:
...
`
Does this help? Or do you need some other output? I can also sent you a link to the output.

**Comment by furlongm** [comment]
I updated your first comment. Need to use three backticks at the beginning and the end of a code block for the formatting to be correct (```).

**Comment by mathiashro** [comment]
Perfect, thank you. Was not aware. Anything else that may help to move forward?

**Comment by furlongm** [comment]
Can you replace

```
                local_ipv4 = parts.popleft()
                if local_ipv4:
                    session['local_ip'] = ip_address(local_ipv4)
                else:
                    session['local_ip'] = ''
                if version.major >= 2 and version.minor >= 4:
                    local_ipv6 = parts.popleft()
                    if local_ipv6:
                        session['local_ip'] = ip_address(local_ipv6)
```
with

```
try:
    session['local_ip'] = ip_address(parts.popleft())
except ValueError:
    session['local_ip'] = ''
```

and see if that helps. Would also probably need to see the full debugging output as there is missing values.

**Comment by mathiashro** [comment]
Replaced the code part:

```
                    except SystemError:
                        pass

                try:
                    session['local_ip'] = ip_address(parts.popleft())
                except ValueError:
                    session['local_ip'] = ''

                session['bytes_recv'] = int(parts.popleft())
                session['bytes_sent'] = int(parts.popleft())
                parts.popleft()
```

Running the command:

```
=== end split line
INFO: Sending command: status 3

DEBUG:
 === begin raw data
TITLE	OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
TIME	Thu May  7 05:44:19 2020	1588823059
HEADER	CLIENT_LIST	Common Name	Real Address	Virtual Address	Virtual IPv6 Address	Bytes Received	Bytes Sent	Connected Since	Connected Since (time_t)	Username	Client ID	Peer ID
CLIENT_LIST	user1	192.168.1.3:57364			125059271	762516296	Wed May  6 03:04:17 2020	1588727057	UNDEF	21	1
CLIENT_LIST	user2	192.168.1.2:50067			896898	1128166	Tue May  5 05:44:34 2020	1588650274	UNDEF	9	5
CLIENT_LIST	user3	192.168.1.5:41226			31189905	28468465	Wed May  6 06:02:52 2020	1588737772	UNDEF	27	0
HEADER	ROUTING_TABLE	Virtual Address	Common Name	Real Address	Last Ref	Last Ref (time_t)
ROUTING_TABLE	aa:b2:0f:00:00:00	user2	192.168.1.2:50067	Thu May  7 04:47:01 2020	1588819621
ROUTING_TABLE	00:b6:9e:42:00:00	user1	192.168.1.3:57364	Thu May  7 05:44:18 2020	1588823058
ROUTING_TABLE	00:0f:00:8e:5c:00	user3	192.168.1.5:41226	Thu May  7 05:44:18 2020	1588823058
GLOBAL_STATS	Max bcast/mcast queue length	5
END

=== end raw data
DEBUG:
 === begin split line
deque([u'TITLE', u'OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019'])
=== end split line
DEBUG:
 === begin split line
deque([u'TIME', u'Thu May  7 05:44:19 2020', u'1588823059'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'CLIENT_LIST', u'Common Name', u'Real Address', u'Virtual Address', u'Virtual IPv6 Address', u'Bytes Received', u'Bytes Sent', u'Connected Since', u'Connected Since (time_t)', u'Username', u'Client ID', u'Peer ID'])
=== end split line
DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'user1', u'192.168.1.3:57364', u'', u'', u'125059271', u'762516296', u'Wed May  6 03:04:17 2020', u'1588727057', u'UNDEF', u'21', u'1'])
=== end split line
Traceback (most recent call last):
  File "openvpn-monitor.py", line 871, in <module>
    main()
  File "openvpn-monitor.py", line 849, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 224, in collect_data
    vpn['sessions'] = self.parse_status(status, vpn['version'])
  File "openvpn-monitor.py", line 428, in parse_status
    session['bytes_recv'] = int(parts.popleft())
ValueError: invalid literal for int() with base 10: ''
````

As we see currently there are only IPv4 Clients connected at the TAP interface. I'll try to provide a output soon once a IPv6 client will join.

**Comment by mathiashro** [comment]
Was my answer somehow helpful? Do we need another run which includes IPv4 and IPv6 clients again? If yes I can let it run on another instance we I currently to see mixed clients connected.

Thank you.

**Comment by furlongm** [comment]
It was helpful - but looks like a different bug!

Yes, another run with mixed clients would help too.

**Comment by mathiashro** [comment]
Here the output:
```
# python openvpn-monitor.py -d > index.html
INFO: Using config file: ./openvpn-monitor.conf
DEBUG:
 === begin section
{u'datetime_format': '%d/%m/%Y %H:%M:%S', u'maps': 'False', u'site': 'Example', u'geoip_data': '/var/lib/GeoIP/GeoLite2-City.mmdb'}
=== end section
DEBUG:
 === begin section
{'host': 'localhost', 'show_disconnect': False, 'port': '7505', 'name': 'Staff VPN'}
=== end section
WARNING: No compatible geoip1 or geoip2 data/libraries found.
INFO: Sending command: version

DEBUG:
 === begin raw data
OpenVPN Version: OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
Management Version: 1
END

=== end raw data
INFO: Sending command: state

DEBUG:
 === begin raw data
1589463228,CONNECTED,SUCCESS,10.1.0.1,,,,
END

=== end raw data
DEBUG:
 === begin split line
[u'1589463228', u'CONNECTED', u'SUCCESS', u'10.1.0.1', u'', u'', u'', u'']
=== end split line
DEBUG:
 === begin split line
[u'END']
=== end split line
INFO: Sending command: load-stats

DEBUG:
 === begin raw data
SUCCESS: nclients=9,bytesin=44281294484,bytesout=60487261413

=== end raw data
DEBUG:
 === begin split line
[u'nclients=9', u'bytesin=44281294484', u'bytesout=60487261413\r\n']
=== end split line
INFO: Sending command: status 3

DEBUG:
 === begin raw data
TITLE	OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019
TIME	Sun May 24 07:23:53 2020	1590297833
HEADER	CLIENT_LIST	Common Name	Real Address	Virtual Address	Virtual IPv6 Address	Bytes Received	Bytes Sent	Connected Since	Connected Since (time_t)	Username	Client ID	Peer ID
CLIENT_LIST	user1	1.1.252.137:54372	10.2.2.209		34109357	35974667	Sun May 24 05:45:10 2020	1590291910	UNDEF	758	5
CLIENT_LIST	user2	2003:1:1:1:1:1:fe16:3cf2	10.2.1.31		215555559	227075398	Sat May 23 20:46:22 2020	1590259582	UNDEF	726
CLIENT_LIST	user3	1.1.100.242:44975	10.2.2.230		33923097755291161918	Thu May 14 15:34:25 2020	1589463265	UNDEF	8	8
CLIENT_LIST	user4	2001:1:1:1:1:e4ff:fe6d:944f	10.2.1.221		635015051	672795831	Sat May 23 00:20:51 2020	1590186051	UNDEF	664
CLIENT_LIST	user5	1.1.252.42:58491	10.2.1.120		14599003112298880117	Wed May 20 01:08:12 2020	1589929692	UNDEF	430	1
CLIENT_LIST	user6	1.3.241.200:54586	10.2.2.254		68323844706001863318	Thu May 14 15:34:25 2020	1589463265	UNDEF	0	0
CLIENT_LIST	user7	1.3.241.206:44182	10.2.2.190		47408959547139230146	Thu May 14 15:34:25 2020	1589463265	UNDEF	3	3
CLIENT_LIST	user8	89.245.119.88:36833	10.2.3.30		52064228885336993930	Thu May 14 15:34:25 2020	1589463265	UNDEF	2	2
CLIENT_LIST	user9	1.3.241.206:57864	10.2.2.189		548469608414758371405	Thu May 14 15:34:25 2020	1589463265	UNDEF	7	7
HEADER	ROUTING_TABLE	Virtual Address	Common Name	Real Address	Last Ref	Last Ref (time_t)
ROUTING_TABLE	7e:7c:2b:37:36:e6	user7	1.3.241.206:44182	Sun May 24 07:23:21 2020	1590297801
ROUTING_TABLE	e2:f3:c5:72:97:43	user5	1.1.252.42:58491	Sun May 24 07:23:42 2020	1590297822
ROUTING_TABLE	1e:c3:ab:29:c4:ec	user4	2001:1:1:1:1:e4ff:fe6d:944f	Sun May 24 07:21:54 2020	1590297714
ROUTING_TABLE	22:a5:e6:1e:e1:01	user2	2003:1:1:1:1:1:fe16:3cf2	Sun May 24 07:23:11 2020	1590297791
ROUTING_TABLE	92:9e:a5:56:1d:58	user3	1.1.100.242:44975	Sun May 24 07:23:53 2020	1590297833
ROUTING_TABLE	12:e3:24:aa:c0:32	user6	1.3.241.200:54586	Sun May 24 07:23:27 2020	1590297807
ROUTING_TABLE	a2:a5:33:1d:cc:97	user8	89.245.119.88:36833	Sun May 24 07:21:42 2020	1590297702
ROUTING_TABLE	be:b5:4e:7c:e5:02	user1	1.1.252.137:54372	Sun May 24 07:22:40 2020	1590297760
ROUTING_TABLE	02:2c:91:93:45:d9	user9	1.3.241.206:57864	Sun May 24 07:23:53 2020	1590297833
GLOBAL_STATS	Max bcast/mcast queue length	12
END

=== end raw data
DEBUG:
 === begin split line
deque([u'TITLE', u'OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 20 2019'])
=== end split line
DEBUG:
 === begin split line
deque([u'TIME', u'Sun May 24 07:23:53 2020', u'1590297833'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'CLIENT_LIST', u'Common Name', u'Real Address', u'Virtual Address', u'Virtual IPv6 Address', u'Bytes Received', u'Bytes Sent', u'Connected Since', u'Connected Since (time_t)', u'Username', u'Client ID', u'Peer ID'])
=== end split line
DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'user1', u'1.1.252.137:54372', u'10.2.2.209', u'', u'34109357', u'35974667', u'Sun May 24 05:45:10 2020', u'1590291910', u'UNDEF', u'758', u'5'])
=== end split line
Traceback (most recent call last):
  File "openvpn-monitor.py", line 871, in <module>
    main()
  File "openvpn-monitor.py", line 849, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 212, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 224, in collect_data
    vpn['sessions'] = self.parse_status(status, vpn['version'])
  File "openvpn-monitor.py", line 428, in parse_status
    session['bytes_recv'] = int(parts.popleft())
ValueError: invalid literal for int() with base 10: ''
```

**Comment by furlongm** [comment]
Can you make sure you are running the latest version from `master`? It looks like the `ValueError` bug you are hitting is already fixed there.

**Comment by furlongm** [comment]
@mathiashro did that fix it for you?

**Comment by furlongm** [comment]
Closing due to lack of response. As far as I can, these bugs are all fixed on master. Feel free to re-open if that is not the case.
