### ISSUE TITLE
Error: 500 Internal Server Error - The address %s is not in the database." % ip_address

### ISSUE THREAD

**Issue by blessendor** [furlongm/openvpn-monitor#167]
It worked very good for a long time, until today.
All stuff running inside LXC container, as well as OpenVPN server. 
Can't restart container now, maybe later tonight, to check if it can fix an error.

**Nginx error form uwsgi:**

Error: 500 Internal Server Error

Sorry, the requested URL 'http://10.1.1.1/openvpn-monitor/' caused an error:

Internal Server Error

**Debug** (real client IP was changed):

DEBUG:
 === begin split line
deque([u'TITLE', u'OpenVPN 2.4.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017'])
=== end split line
DEBUG:
 === begin split line
deque([u'TIME', u'Sat Jul 11 10:40:01 2020', u'1594453201'])
=== end split line
DEBUG:
 === begin split line
deque([u'HEADER', u'CLIENT_LIST', u'Common Name', u'Real Address', u'Virtual Address', u'Virtual IPv6 Address', u'Bytes Received', u'Bytes Sent', u'Connected Since', u'Connected Since (time_t)', u'Username', u'Client ID', u'Peer ID'])
=== end split line
DEBUG:
 === begin split line
deque([u'CLIENT_LIST', u'018_MKT_TV', u'54.151.239.11:34325', u'10.1.2.2', u'', u'406646', u'329424', u'Fri Jul 10 23:10:19 2020', u'1594411819', u'UNDEF', u'0', u'0'])
=== end split line
Traceback (most recent call last):
  File "openvpn-monitor.py", line 832, in <module>
    main()
  File "openvpn-monitor.py", line 810, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 197, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 209, in collect_data
    vpn['sessions'] = self.parse_status(status, vpn['version'])
  File "openvpn-monitor.py", line 399, in parse_status
    gir = gi.city(str(session['remote_ip']))
  File "/srv/openvpn-monitor/local/lib/python2.7/site-packages/geoip2/database.py", line 114, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/srv/openvpn-monitor/local/lib/python2.7/site-packages/geoip2/database.py", line 195, in _model_for
    record = self._get(types, ip_address)
  File "/srv/openvpn-monitor/local/lib/python2.7/site-packages/geoip2/database.py", line 191, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 54.151.239.11 is not in the database.
(openvpn-monitor) root@vpn /srv/openvpn-monitor#

**Comment by blessendor** [comment]
There was GeoIP DB problem. 
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
