### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by guossf** [furlongm/openvpn-monitor#239]
INFO: Sending command: version

INFO: Sending command: state

Traceback (most recent call last):
  File "/srv/openvpn-monitor/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/srv/openvpn-monitor/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 916, in get_slash
    return render()
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 904, in render
    main(**kwargs)
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 865, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 214, in __init__
    self.collect_data(vpn)
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 222, in collect_data
    vpn['state'] = self.parse_state(state)
  File "/srv/openvpn-monitor/lib/python3.6/site-packages/openvpn-monitor.py", line 324, in parse_state
    if parts[4]:
IndexError: list index out of range
-----------------------------------------
hi, how to solve the above problems ?

**Comment by furlongm** [comment]
Which version of openvpn are you using?

Can you run openvpn-monitor.py on the command line with the debug option?

**Comment by guossf** [comment]
used OpenVPN 2.0.9 .
----------------------------------------
(openvpn-monitor) sh-4.2# python3 openvpn-monitor.py  -d
WARNING: Config file does not exist or is unreadable: ./openvpn-monitor.conf
WARNING: Config file does not exist or is unreadable: /srv/openvpn-monitor/etc/openvpn-monitor.conf
INFO: Using default settings => localhost:5555
WARNING: No compatible geoip1 or geoip2 data/libraries found.
INFO: Sending command: version

DEBUG:
 === begin raw data
OpenVPN Version: OpenVPN 2.0.9 x86_64-unknown-linux [SSL] [LZO] [EPOLL] built on Feb 11 2022
Management Version: 1
END

=== end raw data
INFO: Sending command: state

DEBUG:
 === begin raw data
1645007299,CONNECTED,SUCCESS,10.8.0.1
END

=== end raw data
DEBUG:
 === begin split line
['1645007299', 'CONNECTED', 'SUCCESS', '10.8.0.1']
=== end split line
Traceback (most recent call last):
  File "openvpn-monitor.py", line 887, in <module>
    main()
  File "openvpn-monitor.py", line 865, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 214, in __init__
    self.collect_data(vpn)
  File "openvpn-monitor.py", line 222, in collect_data
    vpn['state'] = self.parse_state(state)
  File "openvpn-monitor.py", line 324, in parse_state
    if parts[4]:
IndexError: list index out of range

**Comment by furlongm** [comment]
Looks like 2.0.9 was released in 2013. Could you try a newer version of openvpn?

**Comment by guossf** [comment]
OpenVPN 2.4.8 version is normal.
