### ISSUE TITLE
Cropped output

### ISSUE THREAD

**Issue by Meisterschueler** [furlongm/openvpn-monitor#8]
The output is cropped:
![openvpn_cropped_output](https://cloud.githubusercontent.com/assets/4268343/15466117/4c5c0800-20d8-11e6-88e4-af027387f419.png)

Last rows in the html are:
```
<tr>
<td>EDNC</td>
<td>10.8.0.61</td>
<td>91.15.155.167</td>
<td>41217</td>
```

**Comment by furlongm** [comment]
Is there an error in the web server log files? Or an error if you run the command on the CLI?

**Comment by Meisterschueler** [comment]
In the apache error log files there is always this error:
```
Traceback (most recent call last):
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 646, in <module>
    main()
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 622, in main
    OpenvpnHtmlPrinter(cfg, monitor)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 353, in __init__
    self.print_vpn(vpn)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 518, in print_vpn
    self.print_session_table(vpn_mode, vpn_sessions)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 573, in print_session_table
    self.print_server_session(session)
  File "/var/www/html/openvpn-monitor/openvpn-monitor.py", line 547, in print_server_session
    full_location = '{0!s}, {1!s}'.format(city, country)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 1: invalid start byte
```

**Comment by furlongm** [comment]
Can you add a print statement before line 457 to see what the values for
city and country are?

**Comment by Meisterschueler** [comment]
It fails with the city. 
```
print(city)
print(city.decode('ISO-8859-1'))
```
returns
```
Rothenb�rg
Rothenbürg
```
