### ISSUE TITLE
no such file or Dir: GeoLite2-City.mmdb Debian

### ISSUE THREAD

**Issue by deitChi** [furlongm/openvpn-monitor#86]
```
INFO: Using config file: ./openvpn-monitor.conf
DEBUG:
 === begin section
{u'datetime_format': '%d/%m/%Y %H:%M:%S', u'maps': 'True', u'site': 'Openvpn', u'geoip_data': '/var/lib/GeoIP/GeoLite2-City.mmdb'}
=== end section
DEBUG:
 === begin section
{'host': 'localhost', 'show_disconnect': False, 'port': '5555', 'name': 'UK_2-VPN'}
=== end section
Traceback (most recent call last):
  File "openvpn-monitor.py", line 825, in <module>
    main()
  File "openvpn-monitor.py", line 803, in main
    monitor = OpenvpnMgmtInterface(cfg, **kwargs)
  File "openvpn-monitor.py", line 184, in __init__
    self.gi = database.Reader(geoip_data)
  File "/usr/lib/python2.7/dist-packages/geoip2/database.py", line 82, in __init__
    self._db_reader = maxminddb.open_database(filename, mode)
  File "/usr/lib/python2.7/dist-packages/maxminddb/__init__.py", line 32, in open_database
    return maxminddb.extension.Reader(database)
IOError: No such file or directory: '/var/lib/GeoIP/GeoLite2-City.mmdb'
```

When installing the Deb Packages, I get a directory in /var/lib/GeoIP/ but it's empy. I believe that it's just not a repo on Debian. - I've tried setting maps=False, but it still returns the same error.
Is there a way to disable mapping and still run the service?

**Comment by furlongm** [comment]
What version of debian are you using? Have you installed the geoipupdate pckage?

**Comment by furlongm** [comment]
I can double check this later, but I seem to recall needing to copy `/usr/share/doc/geoipupdate/examples/GeoIP.conf.default` to `/etc/GeoIP.conf` and running geoipupdate manually. (or maybe to `/etc/geoip/GeoIP.conf`).

**Comment by furlongm** [comment]
Closing for now. Feel free to re-open if that did not solve your issue.
